# Generated by Django 5.1.4 on 2024-12-29 22:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usersmanage", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=25,
            ),
        ),
    ]
