# Generated by Django 5.1.4 on 2025-01-29 17:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usersmanage", "0003_alter_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "pending"),
                    ("completed", "completed"),
                    ("cancelled", "cancelled"),
                ],
                default="pending",
                max_length=25,
            ),
        ),
    ]
