# Generated by Django 5.1.4 on 2025-06-30 16:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usersmanage", "0004_alter_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegramuser",
            name="language",
            field=models.CharField(
                choices=[("en", "English"), ("ru", "Russian")],
                default="en",
                max_length=10,
                verbose_name="language",
            ),
        ),
    ]
